version: '3.6'

services:
  app:
    build: .
    ports:
      - ${SERVER_PORT}:8080
    volumes:
      - ./:/app/
    restart: always
    environment:
      DATABASE_HOST: data
    command: yarn start:dev
  data:
    image: mysql:5.7
    ports:
      - 33060:3306
    volumes:
      - .mysql:/var/lib/mysql
      - ./schemas/:/docker-entrypoint-initdb.d/:ro
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
