CREATE TABLE `orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `origin` POINT NOT NULL,
  `destination` POINT NOT NULL,
  `status` ENUM('UNASSIGNED', 'TAKEN', 'CANCELED') NOT NULL,
  `distance` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));